name: Publish to NPM with Attestations

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional, uses package.json version if not specified)'
        required: false
        type: string

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm run test:run
        
      - name: Build package
        run: npm run build
        
      - name: Get package info
        id: package-info
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          # npm pack removes @ and / from scoped package names for the tarball filename
          TARBALL_NAME=$(node -p "require('./package.json').name.replace('@', '').replace('/', '-')")
          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "tarball=${TARBALL_NAME}-${PACKAGE_VERSION}.tgz" >> $GITHUB_OUTPUT
          
      - name: Create package tarball
        run: npm pack
        
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Generate build attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ steps.package-info.outputs.tarball }}'
          
      - name: Generate SLSA attestation for built package
        uses: actions/attest-sbom@v1
        with:
          subject-path: '${{ steps.package-info.outputs.tarball }}'
          sbom-path: '${{ steps.package-info.outputs.tarball }}'
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: |
            ${{ steps.package-info.outputs.tarball }}
            dist/
          retention-days: 30